[general]
fullscreen = false
early-exit = true
copy-command = "wl-copy"
output-filename = "~/Pictures/Screenshots/Sreenshot_%Y-%m-%d_%H:%M:%S.png"
save-after-copy = true
disable-notifications = true
actions-on-enter = ["save-to-clipboard", "save-to-file", "exit"]
actions-on-escape = ["save-to-clipboard", "save-to-file", "exit"]
no-window-decoration = true

[color-palette]
palette = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]
custom = []
